/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 * @file JframeInicioGUI.java
 * @brief 
 * @author
 *         - Sebastian Castro - 2359435
 *         - Karol Burbano - 2359305
 *         -Veronica Mujica - 2359406
 *         -Jeidy Murillo - 2359310 
 */
public class JFrameInicioGUI extends javax.swing.JFrame {

    /**
     * Creates new form JFrameInicioGUI
     */
    public JFrameInicioGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonJugar = new javax.swing.JButton();
        jButtonComo = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelSub = new javax.swing.JLabel();
        jLabelCentral = new javax.swing.JLabel();
        jLabelFondoInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("juego");
        setResizable(false);
        getContentPane().setLayout(null);

        jButtonJugar.setBackground(new java.awt.Color(242, 242, 242));
        jButtonJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/jugar.png"))); // NOI18N
        jButtonJugar.setContentAreaFilled(false);
        jButtonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJugar);
        jButtonJugar.setBounds(370, 390, 370, 90);

        jButtonComo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comojugar.png"))); // NOI18N
        jButtonComo.setContentAreaFilled(false);
        jButtonComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonComo);
        jButtonComo.setBounds(350, 510, 410, 80);

        jLabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setFont(new java.awt.Font("{¡Estoy Bueno!}", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("BIENVENIDOS AL JUEGO ");
        getContentPane().add(jLabelTitulo);
        jLabelTitulo.setBounds(420, 50, 280, 40);

        jLabelSub.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSub.setFont(new java.awt.Font("{¡Estoy Bueno!}", 1, 18)); // NOI18N
        jLabelSub.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSub.setText("...PIEDRA, PAPEL O TIJERAS...");
        getContentPane().add(jLabelSub);
        jLabelSub.setBounds(420, 100, 270, 20);

        jLabelCentral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imgTitulo.png"))); // NOI18N
        getContentPane().add(jLabelCentral);
        jLabelCentral.setBounds(440, 140, 230, 230);

        jLabelFondoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoInicio.png"))); // NOI18N
        getContentPane().add(jLabelFondoInicio);
        jLabelFondoInicio.setBounds(0, 0, 1104, 665);

        setSize(new java.awt.Dimension(1118, 665));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //Define el método maneja el evento de clic del botón de como jugar, lo que hace que se abra la pantalla de como jugar del juego y se cierre la ventana actual.
    private void jButtonComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComoActionPerformed
        // Crea una nueva instancia de la pantalla de como jugar del juego.
        JFrameComoJugarGUI newframe = new JFrameComoJugarGUI();
        // Hace visible la nueva pantalla.
        newframe.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jButtonComoActionPerformed
    
    //Define el método maneja el evento de clic del botón de jugar, lo que hace que se abra la pantalla del juego y se cierre la ventana actual.
    private void jButtonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugarActionPerformed
        // Crea una nueva instancia de la pantalla del juego.
        JFrameJuegoGUI newframe = new JFrameJuegoGUI();
        // Hace visible la nueva pantalla.
        newframe.setVisible(true);
        // Cierra la ventana actual.
        this.dispose();
    }//GEN-LAST:event_jButtonJugarActionPerformed

    /**
     * @param args the command line arguments
     */
    //El método main configura el look and feel de Nimbus para la aplicación y lanza la interfaz gráfica de usuario principal del juego.
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameInicioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameInicioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameInicioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameInicioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameInicioGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComo;
    private javax.swing.JButton jButtonJugar;
    private javax.swing.JLabel jLabelCentral;
    private javax.swing.JLabel jLabelFondoInicio;
    private javax.swing.JLabel jLabelSub;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables
}
