/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 * @file JframeComoJugarGUI.java
 * @brief 
 * @author
 *         - Sebastian Castro - 2359435
 *         - Karol Burbano - 2359305
 *         -Veronica Mujica - 2359406
 *         -Jeidy Murillo - 2359310 
 */

import javax.swing.JOptionPane;


public class JFrameComoJugarGUI extends javax.swing.JFrame {


    /**
     * Creates new form JFrameJuegoGUI
     */
    public JFrameComoJugarGUI() {
        initComponents();

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInfoAtras = new javax.swing.JLabel();
        jLabelInfoResultadoRonda = new javax.swing.JLabel();
        jLabelInfoSeleccion = new javax.swing.JLabel();
        jLabelInfoOpciones = new javax.swing.JLabel();
        jLabelInfoRondas = new javax.swing.JLabel();
        jLabelInfoSeleccionH = new javax.swing.JLabel();
        jLabelInfoResultado = new javax.swing.JLabel();
        jButtonPapel = new javax.swing.JButton();
        jButtonPiedra = new javax.swing.JButton();
        jButtonTijeras = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jLabelConteo = new javax.swing.JLabel();
        jLabelVida = new javax.swing.JLabel();
        jLabelVs = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelPiedraP = new javax.swing.JLabel();
        jLabelPiedraH = new javax.swing.JLabel();
        jLabelTitulo1 = new javax.swing.JLabel();
        jLabelTitulo2 = new javax.swing.JLabel();
        jLabelTitulo3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListInfo = new javax.swing.JList<>();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1104, 665));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelInfoAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info.png"))); // NOI18N
        jLabelInfoAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInfoAtrasMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelInfoAtras);
        jLabelInfoAtras.setBounds(70, 20, 80, 60);

        jLabelInfoResultadoRonda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info.png"))); // NOI18N
        jLabelInfoResultadoRonda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInfoResultadoRondaMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelInfoResultadoRonda);
        jLabelInfoResultadoRonda.setBounds(1000, 150, 80, 60);

        jLabelInfoSeleccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info.png"))); // NOI18N
        jLabelInfoSeleccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInfoSeleccionMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelInfoSeleccion);
        jLabelInfoSeleccion.setBounds(550, 270, 80, 60);

        jLabelInfoOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info.png"))); // NOI18N
        jLabelInfoOpciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInfoOpcionesMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelInfoOpciones);
        jLabelInfoOpciones.setBounds(30, 480, 80, 60);

        jLabelInfoRondas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info.png"))); // NOI18N
        jLabelInfoRondas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInfoRondasMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelInfoRondas);
        jLabelInfoRondas.setBounds(970, 500, 80, 60);

        jLabelInfoSeleccionH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info.png"))); // NOI18N
        jLabelInfoSeleccionH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInfoSeleccionHMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelInfoSeleccionH);
        jLabelInfoSeleccionH.setBounds(220, 260, 80, 60);

        jLabelInfoResultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info.png"))); // NOI18N
        jLabelInfoResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInfoResultadoMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelInfoResultado);
        jLabelInfoResultado.setBounds(350, 120, 80, 60);

        jButtonPapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/papelH.png"))); // NOI18N
        jButtonPapel.setBorderPainted(false);
        jButtonPapel.setContentAreaFilled(false);
        jButtonPapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPapelActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPapel);
        jButtonPapel.setBounds(280, 370, 210, 240);

        jButtonPiedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/piedraH.png"))); // NOI18N
        jButtonPiedra.setBorderPainted(false);
        jButtonPiedra.setContentAreaFilled(false);
        jButtonPiedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPiedraActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPiedra);
        jButtonPiedra.setBounds(80, 370, 210, 240);

        jButtonTijeras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tijeresH.png"))); // NOI18N
        jButtonTijeras.setBorderPainted(false);
        jButtonTijeras.setContentAreaFilled(false);
        jButtonTijeras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTijerasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTijeras);
        jButtonTijeras.setBounds(480, 370, 210, 240);

        jButtonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hacia-atras.png"))); // NOI18N
        jButtonVolver.setContentAreaFilled(false);
        jButtonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonVolverMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonVolver);
        jButtonVolver.setBounds(0, 0, 80, 50);

        jLabelConteo.setFont(new java.awt.Font("Meanwhile por Camelot", 3, 50)); // NOI18N
        jLabelConteo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConteo.setText("3210");
        getContentPane().add(jLabelConteo);
        jLabelConteo.setBounds(840, 480, 100, 110);

        jLabelVida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rondas-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabelVida);
        jLabelVida.setBounds(700, 400, 380, 200);

        jLabelVs.setFont(new java.awt.Font("Meanwhile por Camelot", 3, 50)); // NOI18N
        jLabelVs.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVs.setText("vs");
        getContentPane().add(jLabelVs);
        jLabelVs.setBounds(300, 190, 80, 110);

        jLabelTitulo.setFont(new java.awt.Font("Meanwhile por Camelot", 3, 50)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Realiza tu elección");
        getContentPane().add(jLabelTitulo);
        jLabelTitulo.setBounds(280, 20, 680, 110);

        jLabelPiedraP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/piedraPc.png"))); // NOI18N
        getContentPane().add(jLabelPiedraP);
        jLabelPiedraP.setBounds(410, 150, 210, 190);

        jLabelPiedraH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/piedra.png"))); // NOI18N
        getContentPane().add(jLabelPiedraH);
        jLabelPiedraH.setBounds(90, 150, 210, 190);

        jLabelTitulo1.setFont(new java.awt.Font("Meanwhile por Camelot", 3, 18)); // NOI18N
        jLabelTitulo1.setForeground(new java.awt.Color(153, 0, 153));
        jLabelTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo1.setText("RESULTAdo");
        getContentPane().add(jLabelTitulo1);
        jLabelTitulo1.setBounds(260, 170, 170, 40);

        jLabelTitulo2.setFont(new java.awt.Font("Meanwhile por Camelot", 3, 18)); // NOI18N
        jLabelTitulo2.setForeground(new java.awt.Color(153, 0, 153));
        jLabelTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo2.setText("RESULTAdo de las tres rondas");
        getContentPane().add(jLabelTitulo2);
        jLabelTitulo2.setBounds(690, 130, 320, 40);

        jLabelTitulo3.setFont(new java.awt.Font("Meanwhile por Camelot", 3, 20)); // NOI18N
        jLabelTitulo3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo3.setText("¿como jugar ? selecciona los iconos de exclamación para obtener mas información");
        getContentPane().add(jLabelTitulo3);
        jLabelTitulo3.setBounds(100, 340, 1010, 40);

        jListInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jListInfo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(jListInfo);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(690, 180, 340, 150);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondojugar.png"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 1094, 665);

        setSize(new java.awt.Dimension(1108, 672));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//borrar
    private void jButtonPiedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPiedraActionPerformed

    }//GEN-LAST:event_jButtonPiedraActionPerformed
//borrar
    private void jButtonPapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPapelActionPerformed

    }//GEN-LAST:event_jButtonPapelActionPerformed
//borrar
    private void jButtonTijerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTijerasActionPerformed

    }//GEN-LAST:event_jButtonTijerasActionPerformed
    
    //Define el método maneja el evento de clic del botón de Volver, lo que hace que se abra la pantalla inicial del juego y se cierre la ventana actual.
    private void jButtonVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVolverMouseClicked
        
        // Crea una nueva instancia de la pantalla inicial del juego.
        VistaJuegoGUI newframe = new VistaJuegoGUI();
        
        // Hace visible la nueva pantalla.
        newframe.setVisible(true);
        
        // Cierra la ventana actual.
        this.dispose();      
    }//GEN-LAST:event_jButtonVolverMouseClicked
    
    //Define el método que maneja el evento de clic del ratón en la etiqueta jLabelInfoAtras.
    private void jLabelInfoAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInfoAtrasMouseClicked
       
    }//GEN-LAST:event_jLabelInfoAtrasMouseClicked
    //Define el método que maneja el evento de clic del ratón en la etiqueta jLabelInfoResultado.
    private void jLabelInfoResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInfoResultadoMouseClicked
        
    }//GEN-LAST:event_jLabelInfoResultadoMouseClicked
    //Define el método que maneja el evento de clic del ratón en la etiqueta jLabelInfoSeleccionH.
    private void jLabelInfoSeleccionHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInfoSeleccionHMouseClicked
       
    }//GEN-LAST:event_jLabelInfoSeleccionHMouseClicked
    //Define el método que maneja el evento de clic del ratón en la etiqueta jLabelInfoSeleccion.
    private void jLabelInfoSeleccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInfoSeleccionMouseClicked
        
    }//GEN-LAST:event_jLabelInfoSeleccionMouseClicked
    //Define el método que maneja el evento de clic del ratón en la etiqueta 
    private void jLabelInfoResultadoRondaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInfoResultadoRondaMouseClicked
      
    }//GEN-LAST:event_jLabelInfoResultadoRondaMouseClicked
    //Define el método que maneja el evento de clic del ratón en la etiqueta 
    private void jLabelInfoOpcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInfoOpcionesMouseClicked
        
    }//GEN-LAST:event_jLabelInfoOpcionesMouseClicked
    //Define el método que maneja el evento de clic del ratón en la etiqueta 
    private void jLabelInfoRondasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInfoRondasMouseClicked
       
    }//GEN-LAST:event_jLabelInfoRondasMouseClicked

    /**
     * @param args the command line arguments
     */
    //El método main configura el look and feel de Nimbus para la aplicación y lanza la interfaz gráfica de usuario principal del juego.
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameComoJugarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameComoJugarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameComoJugarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameComoJugarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameComoJugarGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButtonPapel;
    private javax.swing.JButton jButtonPiedra;
    private javax.swing.JButton jButtonTijeras;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelConteo;
    private javax.swing.JLabel jLabelInfoAtras;
    private javax.swing.JLabel jLabelInfoOpciones;
    private javax.swing.JLabel jLabelInfoResultado;
    private javax.swing.JLabel jLabelInfoResultadoRonda;
    private javax.swing.JLabel jLabelInfoRondas;
    private javax.swing.JLabel jLabelInfoSeleccion;
    private javax.swing.JLabel jLabelInfoSeleccionH;
    private javax.swing.JLabel jLabelPiedraH;
    private javax.swing.JLabel jLabelPiedraP;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JLabel jLabelTitulo3;
    private javax.swing.JLabel jLabelVida;
    private javax.swing.JLabel jLabelVs;
    private javax.swing.JList<String> jListInfo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
